Allow multiple files to be updated at once
liip/RMT pull request #147
Opened 2019-02-18 15:12 UTC by Jonathanm10

2019-02-19 13:22 UTC, jeanmonod requested changes
@Jonathanm10 Just two comments, then for me you can merge and release a new version with that feature. Good job 👍

2019-02-19 13:22 UTC, jeanmonod commented on README.md
> +    `const VERSION = '%version%';`
@Jonathanm10 This is not completely clear what the user have to configure. Maybe we should add an example into https://github.com/liip/RMT#configuration-examples WDYT?

2019-02-19 13:22 UTC, jeanmonod commented on src/Liip/RMT/Action/FilesUpdateAction.php
> +    }
No need that empty constructor

2019-02-20 08:44 UTC, seyfahni commented on src/Liip/RMT/Action/UpdateVersionClassAction.php
> + * @deprecated Please use UpdateVersionFilesAction instead
Shouldn't it be instead:
```suggestion
 * @deprecated Please use FilesUpdateAction instead
```

2019-02-20 09:33 UTC, jeanmonod commented on src/Liip/RMT/Action/UpdateVersionClassAction.php
> + * @deprecated Please use UpdateVersionFilesAction instead
Good catch @seyfahni !

2019-02-20 20:52 UTC, merged