Default branch to `main` instead of `master`
liip/RMT pull request #172
Opened 2022-03-30 12:43 UTC by RSickenberg

Allow me to fix this:
https://github.com/liip/RMT/issues/170

2022-03-30 16:05 UTC, RSickenberg commented
Thanks, @jeanmonod for the input! Like I wrote on https://github.com/liip/RMT/pull/172/commits/cd3b975a8f633116b92efd6f99c41581c022ed70, I didn't know about this small repo before so this answers the question I had about this. 

I indeed followed the documentation, but my tests are differing from the CI, I have ~6/7 failures VS 2 (one should be fixed now) on the CI.
The issue must be due to the fact I'm running this on my machine with PHP `8.1.4`. 

I would love to contribute more on a migration script, let me some time to do so 🙂

2022-03-30 16:32 UTC, jeanmonod commented
@RSickenberg Changing the repo is an option to fix the tests. But you are still leaving alone all the users working with a `master` branch. For backward compatibility reason, we need a way to configure the main branch name in the config.
If you can do it, that's great, otherwise I will try to find someone on Lausanne to do it :)

2022-03-31 08:30 UTC, RSickenberg commented
@jeanmonod Sure, I will find a way to take care of that!

2022-03-31 18:35 UTC, RSickenberg commented
Hello @jeanmonod, could you run the tests? 

What do you think of the current approach?

2022-03-31 20:18 UTC, jeanmonod requested changes
Thanks a lot @RSickenberg 

I just did a first review! At this end, it's not an `easy-pick` at all. Sorry for that.

Can I ask you one more thing?  To keep `master` branch name into the functional tests. Like this: 1) It's testing to use a different branch than `main`. So it's ensuring backward compat 2) We don't need to change the embedded Git repo?

2022-03-31 20:18 UTC, jeanmonod commented on src/Liip/RMT/Command/InitCommand.php
> +            )),
I don't like so much this question. If the user is saying `none` at the previous question, then it makes no sense to ask him a branch name.
But I have to admit that in most case users will use Git. Maybe allow also a choice `n=>none`. And adjust a bit the question:

    The default branch you want to use (select none if you are not using a VCS system)

2022-03-31 20:18 UTC, jeanmonod commented on src/Liip/RMT/Config/templates/default-vcs-config.yml.tmpl
> +#  On main, we override the general config
Please also use the `%%main-branch%%` in this comment

2022-03-31 20:18 UTC, jeanmonod commented on src/Liip/RMT/Information/InformationCollector.php
> +        if (!array_key_exists($name, static::$standardRequests)) {
Thanks you IntelliJ 😅

2022-03-31 20:18 UTC, jeanmonod commented on test/Liip/RMT/Tests/Functional/GitTest.php
> -//        $this->manualDebug();
Please keep all this `$this->manualDebug();`, they are very usefully to debug

2022-03-31 20:18 UTC, jeanmonod commented on test/Liip/RMT/Tests/Functional/GitTest.php
> +        self::assertEquals('main', $branch[0]);
What are you testing here? To me this is not testing RMT...

2022-03-31 20:18 UTC, jeanmonod commented on test/Liip/RMT/Tests/Functional/GitTest.php
> +        self::assertEquals('1', $tags[0]);
Same here, I'm not really sure what you are testing. How could this test fail?

2022-04-21 07:54 UTC, RSickenberg commented
Hey @jeanmonod, can you run the tests, please? I saw I checked your comments so you might want to look at it :)

Regards

2022-05-05 09:01 UTC, jeanmonod commented
Hi @RSickenberg,
Sorry for my long silence, but I was off for the past 15 days. I long but very resourcing break :)
I will take a look at your lasted commit as soon as possible

2022-05-05 09:20 UTC, RSickenberg commented
Hello @jeanmonod, no worries! Hope this was a good break 🤗 !

Sure, let me know if you need anything.

2025-12-03 14:03 UTC, dbu commented on test/Liip/RMT/Tests/Unit/VCS/GitTest.php
> +        exec('git checkout main --quiet');
```suggestion
        exec('git checkout master --quiet');
```

2025-12-03 14:09 UTC, dbu commented on test/Liip/RMT/Tests/Functional/GitTest.php
> +        self::assertEquals(['_main_1'], $tags);
sorry for the noise. now i understand whats going on.

```suggestion
        self::assertEquals([sprintf('_%s_1', self::DEFAULT_FUNCTIONAL_BRANCH)], $tags);
```

2025-12-03 14:28 UTC, closed without merging

2025-12-13 11:46 UTC, RSickenberg commented
Anytime @dbu, thanks for the follow-up. This lasted for a long time :D